server:
  port: ${SERVER_PORT:8002}
  shutdown: graceful

logging:
  structured:
    format:
      console: com.fitflow.notif.config.JsonLogFormatter
      file: com.fitflow.notif.config.JsonLogFormatter

spring:
  main:
    banner-mode: "off"
  application:
    name: notif-svc
  datasource:
    url: jdbc:postgresql://${NOTIF_DB_HOST:localhost}:${NOTIF_DB_PORT:55432}/${NOTIF_DB_NAME:notifdb}
    username: ${NOTIF_DB_USER:notif_user}
    password: ${NOTIF_DB_PASSWORD:notif_pass}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

spring.cloud.consul:
  host: ${CONSUL_HOST:localhost}
  port: ${CONSUL_PORT:8500}
  discovery:
    service-name: notif-svc
    port: ${SERVER_PORT:8002}
    health-check-path: /healthz
    health-check-interval: 10s
    health-check-critical-timeout: 30s
    prefer-ip-address: true
